name: neuralhaircut
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.18.5
  - scipy>=1.4.1
  - chumpy>=0.69
  - scikit-image>=0.15
  - opencv>=4.1.1
  - pyyaml>=5.1.1
  - pytorch>=1.6.0
  - torchvision>=0.7.0
  - face-alignment
  - kornia>=0.4.0
  - yacs
  - ninja
  - pip
  - pip:
      - face-alignment